<?php
/* Create by \Cc\Autoload 2017-01-21 03:17:35 */
 return array (
  'class' => 
  array (
    'Cc\\Mvc\\Autenticacion' => 'Autenticacion.php',
    'Cc\\Mvc\\Carnet' => 'Carnet.php',
    'Cc\\Mvc\\ExtendsController' => 'ExtendsControler.php',
    'Cc\\Mvc\\FormEstudiante' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\FormRepresentante' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\FormDocente' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\FormDocenteEditar' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\FormDocenteEditarContrasena' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\TablaModel\\docentes' => 'DBtablaModel\\docentes.php',
    'Cc\\Mvc\\TablaModel\\estudiante' => 'DBtablaModel\\estudiante.php',
    'Cc\\Mvc\\TablaModel\\fotos' => 'DBtablaModel\\fotos.php',
    'Cc\\Mvc\\TablaModel\\representante' => 'DBtablaModel\\representante.php',
    'Cc\\Mvc\\TablaModel\\seccion' => 'DBtablaModel\\seccion.php',
  ),
  'DIRECTORY_SEPARATOR' => '\\',
);