<?php
/* Create by \Cc\Autoload 2016-12-12 06:03:43 */
 return array (
  'class' => 
  array (
    'Cc\\Mvc\\Autenticacion' => 'Autenticacion.php',
    'Cc\\Mvc\\Carnet' => 'Carnet.php',
    'Cc\\Mvc\\ExtendsController' => 'ExtendsControler.php',
    'Cc\\Mvc\\FormEstudiante' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\FormRepresentante' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\FormDocente' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\FormDocenteEditar' => 'ModelosDeFormularios.php',
    'Cc\\Mvc\\FormDocenteEditarContrasena' => 'ModelosDeFormularios.php',
  ),
  'DIRECTORY_SEPARATOR' => '\\',
);